({
	"accountInfo": "Account Information",
	"username": "Username",
	"email": "Email",
	"name": "Name",
	"language": "Language",
	"changePasswordAction": "Change Password...",
	"password": "Password",
	"general": "General",
	"changePassword": "Change password",
	"passwordsMatch": "The two passwords match",
	"passwordsDontMatch": "The two passwords do not match",
	"newPassword": "New password",
	"confirmNewPassword": "Retype new password",
	"confirmPassword": "Confirm password",
	"currentPassword": "Current password",
	"authenticate": "Authenticate",
	"authSuccess": "Authentication was successful",
	"authFail": "Authentication failed",
	"changingPassword": "Changing password...",
	"passwordChangeSuccessful": "Password change successful",
	"authRequired": "Authentication required",
	"attemptsRemaining": "Attempt(s) remaining",
	"program": "Program",
	"action": "Action",
	"vendor": "Vendor",
	"unknown": "(Unknown)",
	"restartDesktopForLangChange": "You must restart the desktop for the language change to occur",
	"passwordDirections": "To change your password, enter your current password in the field below and click <b>Authenticate</b>.<br />After you have authenticated, enter your new password, retype it for verification and click <b>Change Password</b>",
	"sudoExplination": "An application is attempting to perform an action which requires privileges. Authentication is required to perform this action.",
	"enterValidEmail": "Enter a valid email",
	"enterPassword": "Enter a password",
	"enterUsername": "Enter a username",
	"usernameAllreadyTaken": "Username already taken",
	"userCreated": "User created",
	"cannotContain": "Username cannot contain \"%s\""
})
