({
	"close": "Fermer",
	"add": "Ajouter",
	"remove": "Enlever",
	"apply": "Appliquer",
	"open": "Ouvrir",
	"save": "Enregistrer",
	"saveAs": "Enregistrer sous",
	"new": "Nouveau",
	"loading": "chargement...",
	"go": "Allez",
	"export": "Exporter",
	"import": "Importer",
	"upload": "Transférer",
	"download": "Télécharger",
	"up": "Haut",
	"refresh": "Rafraichir",
	"back": "Reculer",
	"forward": "Avancer",
	"yes": "Oui",
	"no": "Non",
	"ok": "OK",
	"cancel": "Annuler",
	"loadOrSave": "Charger/Enregistrer",
	"path": "Chemin",
	"play": "Jouer",
	"pause": "Pause",
	"stop": "Arrêter",
	"volume": "Volume",
	"openFile": "Ouvrir un fichier",
	"openUrl": "Ouvrir une URL",
	"metadata": "Métadata",
	"run": "Exécuter",
	"name": "Nom",
	"url": "URL",
	"icon": "Icône",
	"category": "Catégorie",
	"isCategory": "est la catégorie",
	"untitled": "Sans titre",
	"delete": "Effacer",
	"create": "Créer",
	"error": "Erreur",
	"rename": "Renommer",
	"title": "Titre",
	"date": "Date",
	"markAsRead": "Marqué comme lu",
	"login": "Connecter",
	"create": "Créer",
	"chooseWall": "Choisir un papier peint",
	"total": "Total",
	"remaining": "Restant",
	"used": "Utilisé"
})
