({
	"name": "Nom",
	"sysname": "Nom du système",
	"instance": "Instance",
	"id": "ID",
	"author": "Auteur",
	"version": "Version",
	"maturity": "Maturité",
	"category": "Catégorie",
	"status": "Statut",
	"filetypes": "Types de fichiers",
	"actions": "Actions",
	"active": "Actif",
	"killed": "Terminé",
	"zombie": "Zombie",
	"kill": "Terminer",
	"killSuccess": "L'instance %s a été terminée avec succès.",
	"killFail": "L'instance %s N'a PAS été terminée avec succès.",
	"allreadyKilled": "Ce processus a déjà été terminé ou a quitté.",
	"home": "Accueil",
	"apps": "Applications",
	"users": "Utilisateurs",
	"users": "Utilisateurs",
	"groups": "Groupes",
	"permissions": "Permissions",
	"usersOnline": "Utilisateurs en ligne",
	"diskUsage": "Espace disque",
	"createNewUser": "Créer un nouvel utilisateur",
	"createNewGroup": "Créer un nouveau groupe",
	"name": "Nom",
	"logged": "Connecté",
	"email": "Courriel",
	"lastauth": "Dernière connexion",
	"userDelConfirm": "Confirmer la destruction de l'utilisateur",
	"appDelConfirm": "Confirmer la destruction de l'application",
	"themeDelConfirm": "Confirmer la destruction du thème",
	"groupDelConfirm": "Confirmer la destruction du groupe",
	"delFromSys": "Êtes-vous certain de vouloir effacer %s du système de façon permanente?",
	"chUsersPassword": "Changer le mot de passe de %s",
	"alterPermissions": "Modifier les permissions",
	"installAppPackage": "Installer une nouvelle application",
	"installThemePackage": "Installer un nouveau thème",
	"description": "Description",
	"manageGroupMembersGeneric": "Gérer les membres du groupe",
	"modifyQuotaGeneric": "Modifier le quota",
	"modifyQuota": "Modifier le quota de %s",
	"initial": "Autoriser par défaut",
	"installAppInstructions": "Sélectionnez une application à installer sur votre disque dur",
	"installThemeInstructions": "Sélectionnez un thème à installer sur votre disque dur",
	"appInstallSuccess": "L'application a été installée correctement!",
	"themeInstallSuccess": "Le thème a été installé correctement!",
	"permsFor": "Permissions pour %s",
	"allow": "Autoriser",
	"deny": "Interdire",
	"default": "Défaut",
	"groupAlreadyExists": "Un groupe de ce nom existe déjà",
	"manageGroupMembers": "Gérer les membres de %s",
	"notAssigned": "N'a pas encore été assigné",
	"launchingApp": "Lancement de %s...",
	"themes": "Thèmes",
	"preview": "Prévisualiser",
	"quota": "Quota",
	"unlimited": "Sans limite",
	"compatible": "Compatibilité",
	"notCompatible": "Ce paquet n'est pas comptatible",
	"notCompatibleText": "Le paquet que vous avez installé est possiblement incompatible avec cette version de Lucid. Svp, veuillez vérifier si une version plus récente existe sur le site du fournisseur."
})
