<?php

function desktop_code_location() {
	return '../../desktop/';
}

function desktop_project_name() {
	return 'desktop';
}

function desktop_resource_name($namespace, $file) {
  return $file;
}

function desktop_package_name($namespace, $file) {
  //return;
  $parts = explode('/', $file);
  if ($parts[0] == '_base') {
		return $namespace;
  }
	$file_parts = explode('.', array_pop($parts));
	if (in_array('tests', $parts)) return;
	array_pop($file_parts);
	array_push($parts, implode('.', $file_parts));
	array_unshift($parts, $namespace);
  return implode('.', $parts);
}

?>
