({
	"createFolder": "Crear Carpeta",
	"createFile": "Crear Archivo",
	"createLauncher": "Crear Lanzador",
	"application": "Solicitud",
	"arguments": "Alegaciones",
	"name": "Nombre",
	"createFolderText": "Introduzca el nuevo nombre de carpeta.",
	"createFileText": "Introduzca el nuevo nombre del archivo.",
	"asFile": "como archivo",
	"asZip": "como ZIP (ZIP)",
	"asTgz": "como TGZ (GZIP)",
	"asTbz2": "como TBZ2 (BZIP)",
	"parentErr": "Error: No se puede mover/copiar un directorio en sí mismo",
	"alreadyExists": "Un archivo con ese nombre ya existe",
	"cut": "Corte",
	"copy": "Copie",
	"paste": "Pegue",
	"connFailed": "Error de conexión remota",
	"enterPass": "Ingresar Contraseña",
	"forgetImmediate": "Inmediatamente olvidar",
	"rememberForever": "Recuerde para siempre",
	"connect": "Conectar",
	"cancel": "Cancelar",
	"uploading": "Carga de %s archivo(s)...",
	"uploadingComplete": "Completado la subida",
    "openWith": "Abrir con..."
})
