dojo.provide("desktop.apps.Messenger");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("desktop.apps.Messenger._base");
dojo.require("desktop.apps.Messenger.store");
dojo.require("desktop.apps.Messenger.ui");
dojo.require("desktop.apps.Messenger.io");
dojo.require("desktop.apps.Messenger.sound");
