<?

// --------------------------------------------------------------
// addressbook
// --------------------------------------------------------------
$TEXT['my-addressbook'] = "Il Mio Indirizzario	";
$TEXT['surname'] = "Nome";
$TEXT['familyname'] = "Cognome";
$TEXT['street'] = "Indirizzo";
$TEXT['plz'] = "Codice postale";
$TEXT['city'] = "Citt&agrave;";
$TEXT['phone'] = "Telefono";

$TEXT['add-address'] = "Aggiungere l`indirizzo";
$TEXT['save-address'] = "Salvare l`indirizzo";
$TEXT['no-data'] = "Non c&egrave; disponibile un indirizzo per '{0}'";
$TEXT['number-of-addresses'] = "Ci sono <b>{0}</b> indirizzi nel dati base";

$TEXT['edit'] = "Modifica";
$TEXT['delete'] = "Cancella";

$TEXT['all'] = "Tutto";

// --------------------------------------------------------------
// guestbook
// --------------------------------------------------------------

?>