<?

// --------------------------------------------------------------
// addressbook
// --------------------------------------------------------------
$TEXT['my-addressbook'] = "Mijn Adresboek";
$TEXT['surname'] = "Voornaam";
$TEXT['familyname'] = "Achternaam";
$TEXT['street'] = "Adres";
$TEXT['plz'] = "Postkode";
$TEXT['city'] = "Plaats";
$TEXT['phone'] = "Telefoon";

$TEXT['add-address'] = "Adres toevoegen";
$TEXT['save-address'] = "Adres opslaan";
$TEXT['no-data'] = "Er is geen adres voor '{0}' gevonden";
$TEXT['number-of-addresses'] = "Er zijn <b>{0}</b> adressen in de database aanwezig";

$TEXT['edit'] = "Wijzigen";
$TEXT['delete'] = "Verwijderen";

$TEXT['all'] = "Alles";

// --------------------------------------------------------------
// guestbook
// --------------------------------------------------------------

?>