<?

// --------------------------------------------------------------
// addressbook
// --------------------------------------------------------------
$TEXT['my-addressbook'] = "Mein Adressbuch";
$TEXT['surname'] = "Vorname";
$TEXT['familyname'] = "Nachname";
$TEXT['street'] = "Strasse";
$TEXT['plz'] = "PLZ";
$TEXT['city'] = "Ort";
$TEXT['phone'] = "Telefon";

$TEXT['add-address'] = "Adresse hinzufuegen";
$TEXT['save-address'] = "Adresse abspeichern";
$TEXT['no-data'] = "Keine Adresse für '{0}' verf&uuml;gbar";
$TEXT['number-of-addresses'] = "Es sind insgesamt <b>{0}</b> Adressen in der Datenbank gespeichert";

$TEXT['edit'] = "Bearbeiten";
$TEXT['delete'] = "Loeschen";

$TEXT['all'] = "Alle";

// --------------------------------------------------------------
// guestbook
// --------------------------------------------------------------

?>