<?

// --------------------------------------------------------------
// addressbook
// --------------------------------------------------------------
$TEXT['my-addressbook'] = "My Addressbook";
$TEXT['surname'] = "Surname";
$TEXT['familyname'] = "Familyname";
$TEXT['street'] = "Street";
$TEXT['plz'] = "Zipcode";
$TEXT['city'] = "City";
$TEXT['phone'] = "Phone";

$TEXT['add-address'] = "Add Address";
$TEXT['save-address'] = "Save Address";
$TEXT['no-data'] = "No Address for '{0}' available";
$TEXT['number-of-addresses'] = "There are stored <b>{0}</b> addresses in the database";

$TEXT['edit'] = "Edit";
$TEXT['delete'] = "Delete";

$TEXT['all'] = "All";

// --------------------------------------------------------------
// guestbook
// --------------------------------------------------------------

?>