({
	"helpHeader": "--Consola de Psych Desktop--\nPuedes escribir cualquier javascript quiera evaluar esta consola.\nO, puede usar estos comandos:\n",
	"reloadHelp": "Volver a cargar el escritorio sin necesidad de acceder a",
	"lsHelp": "En la lista de archivos [dir]",
	"catHelp": "Leer el archivo [archivo] y de impresión a cabo en la consola",
	"cdHelp": "cambio de trabajo camino a [dir]",
	"pwdHelp": "muestra el camino actual",
	"mkdirHelp": "Crea el directorio [dir]",
	"rmHelp": "Elimina el archivo o directorio [archivo]",
	"psHelp": "Mostrar los procesos activos",
	"killHelp": "Mata a una instancia/pid",
	"clearHelp": "Claro la consola",
	"echoHelp": "Imprime texto en la consola",
	"logoutHelp": "Registros que de los de escritorio",
	"instance": "instancia",
	"file": "archivo",
	"dir": "dir",
	"text": "texto",
	"usage": "usado",
	"sysCannotBeKilled": "Sistema no puede estar muerto",
	"procKilled": "Proceso muertos",
	"procKillFail": "Proceso no matar",
	"needDirName": "Necesitamos un nombre de directorio!",
	"needFileName": "Necesitamos un nombre de archivo!",
	"unknownError": "Un error desconocido ha ocurridoUn error desconocido ha ocurrido"
})