({
	"helpHeader": "--Console de Psych Desktop--\nVous pouvez utiliser du javascript dans cette console.\nVous pouvez aussi utiliser ces commandes :\n",
	"reloadHelp": "recharger le bureau sans vous déconnecter",
	"lsHelp": "lister les fichiers dans [dir]",
	"catHelp": "lire le fichier [file] et l'afficher dans la console",
	"cdHelp": "changee le chemin d'accès pour [dir]",
	"pwdHelp": "affiche le chemin d'accès actuel",
	"mkdirHelp": "créer le répertoire [dir]",
	"rmHelp": "supprimer le fichier ou le répertoire [file]",
	"psHelp": "afficher les processus en cours",
	"killHelp": "termine une instance/pid",
	"clearHelp": "effacer l'écran",
	"echoHelp": "Affiche le texte dans la console",
	"logoutHelp": "vous déconnecte du Psych Desltop",
	"instance": "instance",
	"file": "fichier",
	"dir": "répertoire",
	"text": "texte",
	"usage": "usage",
	"procKilled": "processus terminé",
	"procKillFail": "le processus n'a pas pu être terminé",
	"needDirName": "vous devez fournir un nom de répertoire!",
	"needFileName": "vous devez fournir un nom de fichier!",
	"unknownError": "Une erreur inconnue a eu lieu"
})
