({
	"createFolder": "Créer un dossier",
	"createFile": "Créer un fichier",
	"createLauncher": "Créer un lanceur",
	"application": "Application",
	"arguments": "Arguments",
	"name": "Nom",
	"createFolderText": "Veuillez entrer le nom du nouveau dossier.",
	"createFileText": "Veuillez entrer le nom du nouveau fichier.",
	"asFile": "As File",
	"asZip": "as ZIP (ZIP)",
	"asTgz": "as TGZ (GZIP)",
	"asTbz2": "as TBZ2 (BZIP)",
	"parentErr": "Erreur: Impossible de déplacer/copier un répertoire sur lui-même",
	"alreadyExists": "Un fichier de ce nom existe déjà",
	"cut": "Couper",
	"copy": "Copier",
	"paste": "Coller",
	"connFailed": "La connexion externe a échoué",
	"enterPass": "Entrez le mot de passe",
	"forgetImmediate": "Oublier immédiatement",
	"rememberForever": "Toujours se souvenir",
	"connect": "Connecté",
	"cancel": "Annuler",
	"uploading": "Transfert du/des fichier/s %s...",
	"uploadingComplete": "Transfert complété",
   "openWith": "Ouvrir avec..."
})
