({
	"Image Viewer": "Visor de imágenes",
	"Katana IDE": "Katana IDE",
	"Web Browser": "Navegador de Internet",
	"File Browser": "Explorador de archivos",
	"Administration Panel": "Panel de Administración",
	"Checkers": "Damas",
	"Calculator": "Calculadora",
    "Contacts": "Contactos",
	"Feed Reader": "Lector de Alimentaciónes",
	"Word Processor": "Procesador de textos",
	"Text Editor": "Editor de textos",
	"Task Manager": "Administrador de Tareas",
	"Terminal": "Consola",
	"Music Player": "Reproductor de Música",
	"Email Client": "Cliente de correo electrónico",
	"MineSweep": "Mina de barrendero",
	"Appearance": "Apariencia",
	"Account Information": "Información de la cuenta",
	"Startup Applications": "Aplicaciones de inicio",
    "Update Manager": "Actualización Manager",
    "Todo": "Lista de tareas"
})
