({
	"close": "Cerrar",
	"add": "Añada",
	"remove": "Elimine",
	"apply": "Aplique",
	"open": "Abierto",
	"save": "Guarde",
	"saveAs": "Guarde como",
	"new": "Nueva",
	"loading": "Cargando...",
	"go": "Vaya",
	"export": "Exportación",
	"import": "Importación",
	"upload": "Sube archivos",
	"download": "Descarge",
	"up": "Sube",
	"refresh": "Actualizar",
	"back": "Espalda",
	"forward": "Adelante",
	"yes": "Sí",
	"no": "No",
	"ok": "OK",
	"cancel": "Cancele",
	"loadOrSave": "Carga/Guarde",
	"path": "Sendero",
	"play": "Detener",
	"pause": "Pausa",
	"stop": "Pare",
	"volume": "Tomo",
	"openFile": "Abra archivo",
	"openUrl": "Abra URL",
	"metadata": "Metadatos",
	"run": "Ejecute",
	"name": "Nombre",
	"url": "URL",
	"icon": "Icono",
	"category": "Categoría",
	"isCategory": "Esta Categoría",
	"untitled": "No titulado",
	"delete": "Borre",
	"create": "Cree",
	"error": "Error",
	"rename": "Cambie nombre",
	"title": "Título",
	"date": "Fecha",
	"login": "Iniciar sesión",
	"create": "Crear"
})