({
	"close": "Cerrar",
	"add": "Añada",
	"remove": "Elimine",
	"apply": "Aplique",
	"open": "Abierto",
	"save": "Guarde",
	"saveAs": "Guarde como",
	"new": "Nueva",
	"loading": "Cargando...",
	"go": "Vaya",
	"export": "Exportación",
	"import": "Importación",
	"upload": "Sube archivos",
	"download": "Descarge",
	"up": "Sube",
	"refresh": "Actualizar",
	"yes": "Sí",
	"no": "No",
	"ok": "OK",
	"cancel": "Cancele",
	"loadOrSave": "Carga/Guarde",
	"path": "Sendero"
})
