({
	"close": "Cerrar",
	"add": "Añada",
	"remove": "Elimine",
	"apply": "Aplique",
	"open": "Abierto",
	"save": "Guarde",
	"saveAs": "Guarde como",
	"new": "Nueva",
	"loading": "Cargando...",
	"go": "Vaya",
	"export": "Exportación",
	"import": "Importación",
	"upload": "Sube archivos",
	"download": "Descarge",
	"up": "Sube",
	"refresh": "Actualizar",
	"yes": "Sí",
	"no": "No",
	"ok": "OK",
	"cancel": "Cancele",
	"loadOrSave": "Carga/Guarde",
	"path": "Sendero",
	"play": "Detener",
	"pause": "Pausa",
	"stop": "Pare",
	"volume": "Tomo",
	"openFile": "Abra archivo",
	"openUrl": "Abra URL",
	"start": "Inicie",
	"easy": "Fácil",
	"medium": "Mediano",
	"hard": "Difícil",
	"youLose": "¡Usted Pierde!",
	"youWin": "¡Usted gana!"
})