({
	"name": "Nombre",
	"instance": "Instancia",
	"id": "ID",
	"author": "Author",
	"email": "Email",
	"version": "Version",
	"maturity": "Maturity",
	"category": "Category",
	"status": "Estado",
	"actions": "Acciones",
	"active": "Activo",
	"killed": "Matado",
	"zombie": "Zombie",
	"kill": "Matar",
	"killSuccess": "Instancia %s fue muerto con éxito.",
	"killFail": "Instancia %s NO fue muerto con éxito.",
	"allreadyKilled": "Este proceso ya se ha muerto o ha salido.",
	"home": "Casa",
	"apps": "Aplicaciones",
	"users": "Usuarios",
	"groups": "Grupos",
	"permissions": "Permisos",
	"usersOnline": "Usuarios en línea",
	"diskUsage": "Uso de disco",
	"createNewUser": "Cree nuevo usuario",
	"username": "Nombre de usuario",
	"name": "Nombre",
	"logged": "Conectados",
	"email": "Correo electrónico",
	"lastauth": "Última Autenticación ",
	"userDelConfirm": "Usuario supresión de confirmación",
	"delUserFromSys": "¿Está seguro de que desea suprimir permanentemente %s desde el sistema?"
})