({
	"name": "Nombre",
	"sysname": "Nombre de Systema",
	"instance": "Instancia",
	"id": "ID",
	"author": "Autor",
	"version": "Versión",
	"maturity": "Madurez",
	"category": "Categoría",
	"status": "Estado",
	"filetypes": "Tipos de archivos",
	"actions": "Acciones",
	"active": "Activo",
	"killed": "Matado",
	"zombie": "Zombi",
	"kill": "Matar",
	"killSuccess": "Instancia %s fue muerto con éxito.",
	"killFail": "Instancia %s NO fue muerto con éxito.",
	"allreadyKilled": "Este proceso ya se ha muerto o ha salido.",
	"home": "Casa",
	"apps": "Aplicaciones",
	"users": "Usuarios",
	"groups": "Grupos",
	"permissions": "Permisos",
	"usersOnline": "Usuarios en línea",
	"diskUsage": "Uso de disco",
	"createNewUser": "Cree nuevo usuario",
	"createNewGroup": "Cree nuevo grupo",
	"name": "Nombre",
	"logged": "Conectados",
	"email": "Correo electrónico",
	"lastauth": "Última Autenticación ",
	"userDelConfirm": "Usuario supresión de confirmación",
	"appDelConfirm": "Aplicación supresión de confirmación",
	"themeDelConfirm": "Tema supresión de confirmación",
	"groupDelConfirm": "Grupo supresión de confirmación",
	"delFromSys": "¿Está seguro de que desea suprimir permanentemente %s desde el sistema?",
	"chUsersPassword": "Cambiar la contraseña de %s",
	"alterPermissions": "Cambie permisos",
	"installAppPackage": "Instalar el paquete de aplicaciones",
	"installThemePackage": "Instalar el paquete de temas",
	"description": "Descripción",
	"manageGroupMembersGeneric": "Administre los miembros del grupo",
	"modifyQuotaGeneric": "Modifique la cuota",
	"modifyQuota": "Modifique la cuota de %s",
	"initial": "Permitir por defecto",
	"installAppInstructions": "Seleccione una aplicación de paquetes a instalar desde su disco duro local",
	"installThemeInstructions": "Seleccione una tema de paquetes a instalar desde su disco duro local",
	"appInstallSuccess": "Aplicación de instalación de paquetes con éxito!",
	"themeInstallSuccess": "Tema de instalación de paquetes con éxito!",
	"allow": "Permiter",
	"deny": "Denegar",
	"default": "Defecto",
	"groupAlreadyExists": "Grupo con ese nombre ya existe",
	"manageGroupMembers": "Administrar los miembros de %s",
	"notAssigned": "Aún no se ha asignado",
	"launchingApp": "Iniciando %s...",
	"themes": "Temas",
	"preview": "Preview",
	"markAsRead": "Marcar como leído",
	"quota": "Cuota",
	"unlimited": "Ilimitado",
	"compatible": "Compatibilidad",
	"notCompatible": "Paquete incompatible",
	"notCompatibleText": "El paquete que ha instalado puede ser incompatible con esta versión de Lucid. Por favor, compruebe el sitio del proveedor para una actualizada versión."
})
