({
	"name": "Nombre",
	"instance": "Instancia",
	"id": "ID",
	"author": "Autor",
	"version": "Versión",
	"maturity": "Madurez",
	"category": "Categoría",
	"status": "Estado",
	"actions": "Acciones",
	"active": "Activo",
	"killed": "Matado",
	"zombie": "Zombie",
	"kill": "Matar",
	"killSuccess": "Instancia %s fue muerto con éxito.",
	"killFail": "Instancia %s NO fue muerto con éxito.",
	"allreadyKilled": "Este proceso ya se ha muerto o ha salido.",
	"home": "Casa",
	"apps": "Aplicaciones",
	"users": "Usuarios",
	"groups": "Grupos",
	"permissions": "Permisos",
	"usersOnline": "Usuarios en línea",
	"diskUsage": "Uso de disco",
	"createNewUser": "Cree nuevo usuario",
	"createNewGroup": "Cree nuevo grupo",
	"name": "Nombre",
	"logged": "Conectados",
	"email": "Correo electrónico",
	"lastauth": "Última Autenticación ",
	"userDelConfirm": "Usuario supresión de confirmación",
	"appDelConfirm": "Aplicación supresión de confirmación",
	"delFromSys": "¿Está seguro de que desea suprimir permanentemente %s desde el sistema?",
	"chUsersPassword": "Cambiar la contraseña de %s",
	"alterPermissions": "Cambie permisos"
})