({
	"accountInfo": "Information sur le compte",
	"username": "Nom d'utilisateur",
	"email": "Courriel",
	"name": "Nom",
	"language": "Langage",
	"changePasswordAction": "Changer le mot de passe...",
	"password": "Mot de passe",
	"general": "Général",
	"changePassword": "Changee le mot de passe",
	"passwordsMatch": "Les deux mots de passe sont identiques",
	"passwordsDontMatch": "Les mots de passe sont différents",
	"newPassword": "Nouveau mot de passe",
	"confirmNewPassword": "Retaper le mot de passe",
	"confirmPassword": "Confirmer le mot de passe",
	"currentPassword": "Mot de passe actuel",
	"authenticate": "Identifier",
	"authSuccess": "Identification correcte",
	"authFail": "Échec de l'identification",
	"changingPassword": "Modification du mot de passe en cours...",
	"passwordChangeSuccessful": "Le mot de passe a été changé",
	"authRequired": "Identification  requise",
	"attemptsRemaining": "Tentative(s) restante(s)",
	"program": "Programme",
	"action": "Action",
	"vendor": "Vendeur",
	"unknown": "(Inconnu)",
	"restartDesktopForLangChange": "Vous devez redémarrer Lucid pour que le changement de langage prenne effet",
	"passwordDirections": "Pour modifier votre mot de passe, saisissez votre mot de passe actuel dans le champ ci-dessous et cliquez sur <b>Identification</b>.<br />Après vous être identifié, saisissez votre nouveau mot de passe deux fois et cliquez sur <b>Changer le mot de passe</b>",
	"sudoExplination": "Une application tente d'exécuter une action privilégiée. Une identification est requise pour exécuter cette action.",
	"enterValidEmail": "Veuillez saisir une adresse de courriel valide",
	"enterPassword": "Entrez un mot de passe",
	"enterUsername": "Entrez un nom d'utilisateur",
	"usernameAllreadyTaken": "Ce nom d'utilisateur existe déjà",
	"userCreated": "L'utilisateur a été créé",
	"cannotContain": "Un nom d'utilisateur ne peut contenir \"%s\""
})
