({
	"accountInfo": "Información de la cuenta",
	"username": "Nombre de usuario",
	"email": "Dirección de correo electrónico",
	"name": "Nombre",
	"changePasswordAction": "Cambie contraseña...",
	"general": "General",
	"changePassword": "Cambie contraseña",
	"passwordsMatch": "Las dos coinciden con las contraseñas",
	"passwordsDontMatch": "Las dos contraseñas no coinciden",
	"newPassword": "Nueva contraseña",
	"confirmNewPassword": "Confirme nueva contraseña",
	"currentPassword": "Contraseña actual",
	"authenticate": "Verifique",
	"authSuccess": "Verificación tuvo éxito",
	"authFail": "Verificación no tuvo éxito",
	"changingPassword": "Cambiar la contraseña...",
	"passwordChangeSuccessful": "Cambio de contraseña éxito",
	"authRequired": "Se requiere verificación",
	"attemptsRemaining": "intento(s) restantes",
	"program": "Programa",
	"action": "Acción",
	"vendor": "Vendor",
	"unknown": "(Desconocido)",
	"passwordDirections": "Para cambiar su contraseña, introduzca su contraseña actual en el campo de abajo y haga clic en <b>Verifique</b>.<br />Después de que haya sido verificado, escribe tu nueva contraseña, vuelva a escribirla para la verificación y haga clic en <b>Cambie contraseña</b>.",
	"sudoExplination": "La solicitud está tratando de realizar una acción que requiere de privilegios. La verificación es necesaria para realizar esta acción."
})