({
	"Image Viewer": "Image Viewer",
	"Katana IDE": "Katana IDE",
	"Web Browser": "Web Browser",
	"File Browser": "File Browser",
	"Administration Panel": "Administration Panel",
    "Checkers": "Checkers",
	"Calculator": "Calculator",
    "Contacts": "Contacts",
	"Feed Reader": "Feed Reader",
	"Word Processor": "Word Processor",
	"Text Editor": "Text Editor",
	"Task Manager": "Task Manager",
	"Terminal": "Terminal",
	"Music Player": "Music Player",
	"Email Client": "Email Client",
	"MineSweep": "MineSweep",
	"Appearance": "Appearance",
	"Account Information": "Account Information",
	"Startup Applications": "Startup Applications",
    "Update Manager": "Update Manager",
    "Todo": "Todo"
})
