({
	"close": "Close",
	"add": "Add",
	"remove": "Remove",
	"apply": "Apply",
	"open": "Open",
	"save": "Save",
	"saveAs": "Save As",
	"new": "New",
	"loading": "loading...",
	"go": "Go",
	"export": "Export",
	"import": "Import",
	"upload": "Upload",
	"download": "Download",
	"up": "Up",
	"refresh": "Refresh",
	"yes": "Yes",
	"no": "No",
	"ok": "OK",
	"cancel": "Cancel",
	"loadOrSave": "Load/Save",
	"path": "Path"
})
