({
	"name": "Name",
	"instance": "Instance",
	"id": "ID",
	"author": "Author",
	"email": "Email",
	"version": "Version",
	"maturity": "Maturity",
	"category": "Category",
	"status": "Status",
	"actions": "Actions",
	"active": "Active",
	"killed": "Killed",
	"zombie": "Zombie",
	"kill": "Kill",
	"killSuccess": "Instance %s was killed sucessfully.",
	"killFail": "Instance %s was NOT killed sucessfully.",
	"allreadyKilled": "This process has already been killed or has exited.",
	"home": "Home",
	"apps": "Apps",
	"users": "Users",
	"groups": "Groups",
	"permissions": "Permissions",
	"usersOnline": "Users online",
	"diskUsage": "Disk Usage",
	"createNewUser": "Create new user",
	"username": "Username",
	"name": "Name",
	"logged": "Logged In",
	"email": "Email",
	"lastauth": "Last Authentication",
	"userDelConfirm": "User deletion confirmation",
	"delUserFromSys": "Are you sure you want to permanently delete %s from the system?"
})